### PR TITLE
MAP@5 scorer for expedia hotel recommendations

### PR DESCRIPTION
**Pull request by LenaRampula**
Custom scorer for the https://www.kaggle.com/c/expedia-hotel-recommendations/overview competition.

### CODE REVIEW

**Comment by SudalaiRajkumar** [comment]
Good one @LenaRampula. Thanks. 

Can we make it more generic to handle map@k instead of map@5? This [link](https://github.com/benhamner/Metrics/blob/master/Python/ml_metrics/average_precision.py) might help in this regard.

Also adding @vopani as a reviewer as he works on recommendation systems currently for DAI.

**Comment by LenaRampula** [comment]
> Good one @LenaRampula. Thanks.
> 
> Can we make it more generic to handle map@k instead of map@5? This [link](https://github.com/benhamner/Metrics/blob/master/Python/ml_metrics/average_precision.py) might help in this regard.
> 
> Also adding @vopani as a reviewer as he works on recommendation systems currently for DAI.

Thanks @SudalaiRajkumar. If we make it generic, you expect the user to edit it before upload?

**Comment by vopani** [comment]
> Thanks @SudalaiRajkumar. If we make it generic, you expect the user to edit it before upload?

It should be possible using recipe params. Will take a look at it.

**Comment by goldentom42** [comment]
Thanks @LenaRampula ! This metric sounds familiar ;-)

**Comment by vopani** [comment]
@LenaRampula Updated scorer for generic MAP@k, please try out and make any other changes (renaming, formatting, description, etc.) desired before merging.

**Comment by arnocandel** [comment]
shouldn't MAP@10 be the same as MAP@3 if there's only 3 classes? currently, if defaults are left at k=10, a 3-class problem would always return 0, no?

**Comment by LenaRampula** [comment]
> shouldn't MAP@10 be the same as MAP@3 if there's only 3 classes? currently, if defaults are left at k=10, a 3-class problem would always return 0, no?

makes sense. I'll update the code

**Pull request merged**
