### PR TITLE
Add DAAL Decision Forest binary classifier.

### PR DESCRIPTION
**Pull request by tomkraljevic**
Still needs improvement regarding predicting probabilities vs. predicting the label.

### CODE REVIEW

**Comment by tomkraljevic** [comment]
they are taking my feedback and will provide wheel files in the future.

so my inclination is to ignore this problem for now with the hope it becomes “normal”.

the recipe itself can have comments (or even a script) documenting the steps to install the packages.

**Comment by tomkraljevic** [comment]
1.  Is there an API life-cycle hook callback that does a setup step?  If such a thing existed then that routine could check if the required packages existed and (somehow) install them if they don't yet exist.

I did not see any examples of this anywhere.

2.  What about the (pretty common) no-internet situation?

**Comment by pseudotensor** [comment]
1. If one requires packages and they are on pypi (or you have your own server) then listing the packages, then one uses `_modules_needed_by_name` or `_global_modules_needed_by_name` to specify which packages we should install.  We could improve that to handle more general package situations.

2. many recipes require packages installed by pip, and the recommended way to handle no internet or your own server is provided in our config.toml file, which is on par with the kind of task you are suggesting they do.  But none of our recipes require this so far, and hopefully wouldn't be needed if not required in general.

I'm still just suggesting the recipe be improved to be more self-contained so it works more generally.  In any case, the recipe would server purpose because either as s3 artifact or local file (if no internet) you'd want to not have the user to have to follow a bunch of external steps if the recipe could have done it.

**Comment by pseudotensor** [comment]
Works, but only for regression fully.  Binary kinda works, but Daal doesn't return probabilities.  Multi-class needs some more work.

**Pull request merged**
