### PR TITLE
% of events in last X days

### PR DESCRIPTION
**Pull request by mtanco**
"IID" group by and TS on target column

### CODE REVIEW

**Comment by goldentom42** [comment]
Michelle, I totally missed the index problem when we do the groupby with rolling window.
I'll rework that part.

**Comment by goldentom42** [comment]
I changed the fit_transform to :
```
    # This function runs during training
    def fit_transform(self, X: dt.Frame, y: np.array = None):

        # values we need to accessible in other parts of DAI
        features = []
        self._output_feature_names = []
        self._feature_desc = []

        # group by and time
        cols_agg = self.col_group.copy()
        cols_agg.append(self.col_date)

        # group by, time, and y
        cols_agg_y = cols_agg.copy()
        cols_agg_y.append('col_target_bin')

        # Move to pandas
        # Pandas index is no 0 to len X - 1
        X = X.to_pandas()

        # Make a 0/1 column for if the event happened or not
        X['col_target_bin'] = (y == self.target_positive).astype(int)

        # Make sure time is time
        X[self.col_date] = pd.to_datetime(X[self.col_date])

        # Make sure we don't use target values at current row
        # We need to sort by date then groupby customer_id and finally shift 1 event
        X = X.sort_values(self.col_date)
        X['col_target_bin'] = X.groupby(self.col_group)['col_target_bin'].shift(1).fillna(0)
        # Go back to original index
        X.sort_index(inplace=True)
        
        # Create a feature for each of the requested days
        # Initialize the feature result with index set, this way features are added in correct row order even
        # if feature comes out with an unordered index
        feats_df = pd.DataFrame(index=X.index)
        for t in self.timespans:
            # Create feature name
            t_days = str(t) + "d"
            # Create the groups
            groups = X[cols_agg_y].groupby(self.col_group)
            # Run through groups
            feat_list = []
            for _key, _df in groups:
                # Sort the group by date, this is required for the rolling per time interval to work
                _df = _df.sort_values(self.col_date)
                # Apply rolling window
                res = _df.set_index(self.col_date)['col_target_bin'].rolling(t_days, min_periods=1).mean()
                # It is not an apply and index may not be the original one
                # Therefore make sure the index is the original one 
                res.index = _df.index
                # Append current result to the list
                feat_list.append(res)
                # print(res)
            # Concat group results and assign to result dataframe
            # Since dataframe is indexed, feature is inluded in the appropriate row_order
            # i.e. pandas make sure index on both sides agree
            feats_df[t_days] = pd.concat(tuple(feat_list), axis=0)

            # Set the column names and descriptions
            self._output_feature_names.append("Y%: " + t_days)
            self._feature_desc.append("Percent of Target with Event in Last " + str(t) + " Days")

        # keep the max days needed of transactions for each person to look up in transform
        time_filter = (
            X[cols_agg].groupby(self.col_group)[self.col_date].transform('max') - X[self.col_date]
        ) <= timedelta(days=max(self.timespans))
        self.lookup_df = X.loc[time_filter].sort_values(self.col_date)

        # :/ return the features
        return feats_df
```

It handles unsorted time events and customers. tested with both ordered and unordered frames and the same results is returned (when both frames are reordered by customer and time).

**Comment by goldentom42** [comment]
Now need to fix the transform...

**Comment by Far0n** [comment]
`rel-1.8.0` @goldentom42, @mtanco why is that merged into 1.8.0 and not 1.8.1?

**Comment by mtanco** [comment]
@Far0n We built it for a customer who is in 1.8.0 so I am only testing there (so far). 1.8.1 testing and master are on the to do list

**Pull request merged**
